### ISSUE TITLE
XtraFinder 1.3.7

### ISSUE THREAD

**Issue by char1eslu** [xcanwin/MacOS-App-Crack#1]
你好，非常感谢Crack这个软件，之前在10.13.1 用这个还可以，但是在10.14 就不行了，--without kext --without debug --without fs 均不行，能否破解个Mojave with SIP 那个版本呢，非常感谢

**Comment by xcanwin** [comment]
> 你好，非常感谢Crack这个软件，之前在10.13.1 用这个还可以，但是在10.14 就不行了，--without kext --without debug --without fs 均不行，能否破解个Mojave with SIP 那个版本呢，非常感谢

已更新最新版，支持多种安装方式后的破解。

**Comment by char1eslu** [comment]
非常感谢更新，但是我10.14.4安装后，csrutil enable ，重启后还是无法启动XtraFinder ，报错，disable后可以正常使用，可能是软件本身的原因吧，不能完全禁用SIP，多谢了
