### ISSUE TITLE
Termius 破解不能永久生效

### ISSUE THREAD

**Issue by rainstorms** [xcanwin/MacOS-App-Crack#2]
你好，
  我已经用 0.5.4v-kcarC-suimreT 实现了破解，并且可以正常使用了。
  但是软件打开后不久就会提示有新版本，让重新打开，重新打开后，破解的功能就又消失了。
  经过测试后发现：只要关闭软件后再打开付费功能就不可以用了，就需要重新破解，破解后的那一次可以使用付费功能！
  我想咨询一下，有没有只要破解一次就可以一直用的方法？因为不太想不关闭软件，也不太想每次使用之前都破解一下！
 谢谢~

**Comment by xcanwin** [comment]
你会出现这个问题可能是因为你网速太快...以至于自动更新时立刻下载完成并且热覆盖了破解版。可以试着购买三级宽带运营商解决。
（咳）为此之后的破解版我都会移除自动更新。已发布新版本。

**Comment by rainstorms** [comment]
哇，棒呆！
已经下载使用了新的版本，目前没发现问题呢！！
如果有问题我会及时反馈！
加油！
希望作者大大出更多的软件~
加油~
