### ISSUE TITLE
Swish --The missing gesture layer for macOS.

### ISSUE THREAD

**Issue by char1eslu** [xcanwin/MacOS-App-Crack#3]
这个软件不知道大佬可有兴趣啊，哈哈哈🤣
[https://highlyopinionated.co/swish](url)

**Comment by xcanwin** [comment]
暂时优先破解我的所需

**Comment by char1eslu** [comment]
好吧，谢谢回复，by the way，XtraFinder好像更新到1.5了，大佬有意向更新不，感谢

**Comment by xcanwin** [comment]
对XtraFinder如此执着，我找时间破解吧

**Comment by char1eslu** [comment]
> 对XtraFinder如此执着，我找时间破解吧

哈哈，谢谢

**Comment by xcanwin** [comment]
已增加Swish，只是处理有点瑕疵，失去了菜单栏的logo，其他功能没问题

**Comment by char1eslu** [comment]
太🐂️了，感谢🙏🏻
