### ISSUE TITLE
Xtrafinder 1.51

### ISSUE THREAD

**Issue by char1eslu** [xcanwin/MacOS-App-Crack#5]
啊，大佬，又更新了，支持了catalina

**Comment by char1eslu** [comment]
啊，大佬，又更新了，支持了catalina

**Comment by char1eslu** [comment]
而且我发现一个网站盗用你的软件，拿去赚钱，唉
https://mac.orsoon.com/Mac/169075.html

**Comment by Gabirel** [comment]
为什么要close？发布了吗？

**Comment by char1eslu** [comment]
> 为什么要close？发布了吗？

没有啊，我实在等不了了。。。就自己买了😥️
